// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: thetan/shared/v1/match_result.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Thetan.Shared.V1 {

  /// <summary>Holder for reflection information generated from thetan/shared/v1/match_result.proto</summary>
  public static partial class MatchResultReflection {

    #region Descriptor
    /// <summary>File descriptor for thetan/shared/v1/match_result.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiN0aGV0YW4vc2hhcmVkL3YxL21hdGNoX3Jlc3VsdC5wcm90bxIQdGhldGFu",
            "LnNoYXJlZC52MSIuChJNYXRjaFJlc3VsdFJlcXVlc3QSGAoHbWF0Y2hJRBgB",
            "IAEoCVIHbWF0Y2hJRCKtBAoRUGxheWVyUmVzdWx0TW9kZWwSGgoIcGxheWVy",
            "SUQYASABKAlSCHBsYXllcklEEhYKBmhlcm9JRBgCIAEoCVIGaGVyb0lEEh4K",
            "Ckhlcm9UeXBlSUQYAyABKAVSCkhlcm9UeXBlSUQSFwoHU2tpbGxfMRgEIAEo",
            "BVIGU2tpbGwxEhcKB1NraWxsXzIYBSABKAVSBlNraWxsMhISCgRLaWxsGAYg",
            "ASgFUgRLaWxsEhQKBURlYXRoGAcgASgFUgVEZWF0aBIiCgxIZXJvRGFtYWdl",
            "SW4YCCABKAVSDEhlcm9EYW1hZ2VJbhIkCg1IZXJvRGFtYWdlT3V0GAkgASgF",
            "Ug1IZXJvRGFtYWdlT3V0Eh4KC1NraWxsXzFfRG1nGAogASgFUglTa2lsbDFE",
            "bWcSHgoLU2tpbGxfMV9Vc2UYCyABKAVSCVNraWxsMVVzZRIeCgtTa2lsbF8y",
            "X0RtZxgMIAEoBVIJU2tpbGwyRG1nEh4KC1NraWxsXzJfVXNlGA0gASgFUglT",
            "a2lsbDJVc2USGAoHRnVyeVVzZRgOIAEoBVIHRnVyeVVzZRIiCgxCYXR0bGVS",
            "ZXN1bHQYDyABKAVSDEJhdHRsZVJlc3VsdBISCgRSYW5rGBAgASgFUgRSYW5r",
            "EhAKA21WUBgRIAEoCFIDbVZQEh4KCnRyaXBsZUtpbGwYEiABKAhSCnRyaXBs",
            "ZUtpbGwSGgoIbWVnYUtpbGwYEyABKAhSCG1lZ2FLaWxsInUKEE1hdGNoUmVz",
            "dWx0UmVwbHkSGAoHbWF0Y2hJRBgBIAEoCVIHbWF0Y2hJRBJHCgxwbGF5ZXJS",
            "ZXN1bHQYAiADKAsyIy50aGV0YW4uc2hhcmVkLnYxLlBsYXllclJlc3VsdE1v",
            "ZGVsUgxwbGF5ZXJSZXN1bHRCnAEKFGNvbS50aGV0YW4uc2hhcmVkLnYxQhBN",
            "YXRjaFJlc3VsdFByb3RvUAFaEHRoZXRhbi5zaGFyZWQudjGiAgNUU1iqAhBU",
            "aGV0YW4uU2hhcmVkLlYxygIQVGhldGFuXFNoYXJlZFxWMeICHFRoZXRhblxT",
            "aGFyZWRcVjFcR1BCTWV0YWRhdGHqAhJUaGV0YW46OlNoYXJlZDo6VjFiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Thetan.Shared.V1.MatchResultRequest), global::Thetan.Shared.V1.MatchResultRequest.Parser, new[]{ "MatchID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Thetan.Shared.V1.PlayerResultModel), global::Thetan.Shared.V1.PlayerResultModel.Parser, new[]{ "PlayerID", "HeroID", "HeroTypeID", "Skill1", "Skill2", "Kill", "Death", "HeroDamageIn", "HeroDamageOut", "Skill1Dmg", "Skill1Use", "Skill2Dmg", "Skill2Use", "FuryUse", "BattleResult", "Rank", "MVP", "TripleKill", "MegaKill" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Thetan.Shared.V1.MatchResultReply), global::Thetan.Shared.V1.MatchResultReply.Parser, new[]{ "MatchID", "PlayerResult" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MatchResultRequest : pb::IMessage<MatchResultRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MatchResultRequest> _parser = new pb::MessageParser<MatchResultRequest>(() => new MatchResultRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MatchResultRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Thetan.Shared.V1.MatchResultReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchResultRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchResultRequest(MatchResultRequest other) : this() {
      matchID_ = other.matchID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchResultRequest Clone() {
      return new MatchResultRequest(this);
    }

    /// <summary>Field number for the "matchID" field.</summary>
    public const int MatchIDFieldNumber = 1;
    private string matchID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MatchID {
      get { return matchID_; }
      set {
        matchID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MatchResultRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MatchResultRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MatchID != other.MatchID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MatchID.Length != 0) hash ^= MatchID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MatchID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MatchID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MatchID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MatchID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MatchID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MatchID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MatchResultRequest other) {
      if (other == null) {
        return;
      }
      if (other.MatchID.Length != 0) {
        MatchID = other.MatchID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MatchID = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MatchID = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PlayerResultModel : pb::IMessage<PlayerResultModel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerResultModel> _parser = new pb::MessageParser<PlayerResultModel>(() => new PlayerResultModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerResultModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Thetan.Shared.V1.MatchResultReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerResultModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerResultModel(PlayerResultModel other) : this() {
      playerID_ = other.playerID_;
      heroID_ = other.heroID_;
      heroTypeID_ = other.heroTypeID_;
      skill1_ = other.skill1_;
      skill2_ = other.skill2_;
      kill_ = other.kill_;
      death_ = other.death_;
      heroDamageIn_ = other.heroDamageIn_;
      heroDamageOut_ = other.heroDamageOut_;
      skill1Dmg_ = other.skill1Dmg_;
      skill1Use_ = other.skill1Use_;
      skill2Dmg_ = other.skill2Dmg_;
      skill2Use_ = other.skill2Use_;
      furyUse_ = other.furyUse_;
      battleResult_ = other.battleResult_;
      rank_ = other.rank_;
      mVP_ = other.mVP_;
      tripleKill_ = other.tripleKill_;
      megaKill_ = other.megaKill_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerResultModel Clone() {
      return new PlayerResultModel(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private string playerID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlayerID {
      get { return playerID_; }
      set {
        playerID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "heroID" field.</summary>
    public const int HeroIDFieldNumber = 2;
    private string heroID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HeroID {
      get { return heroID_; }
      set {
        heroID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HeroTypeID" field.</summary>
    public const int HeroTypeIDFieldNumber = 3;
    private int heroTypeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HeroTypeID {
      get { return heroTypeID_; }
      set {
        heroTypeID_ = value;
      }
    }

    /// <summary>Field number for the "Skill_1" field.</summary>
    public const int Skill1FieldNumber = 4;
    private int skill1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Skill1 {
      get { return skill1_; }
      set {
        skill1_ = value;
      }
    }

    /// <summary>Field number for the "Skill_2" field.</summary>
    public const int Skill2FieldNumber = 5;
    private int skill2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Skill2 {
      get { return skill2_; }
      set {
        skill2_ = value;
      }
    }

    /// <summary>Field number for the "Kill" field.</summary>
    public const int KillFieldNumber = 6;
    private int kill_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Kill {
      get { return kill_; }
      set {
        kill_ = value;
      }
    }

    /// <summary>Field number for the "Death" field.</summary>
    public const int DeathFieldNumber = 7;
    private int death_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Death {
      get { return death_; }
      set {
        death_ = value;
      }
    }

    /// <summary>Field number for the "HeroDamageIn" field.</summary>
    public const int HeroDamageInFieldNumber = 8;
    private int heroDamageIn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HeroDamageIn {
      get { return heroDamageIn_; }
      set {
        heroDamageIn_ = value;
      }
    }

    /// <summary>Field number for the "HeroDamageOut" field.</summary>
    public const int HeroDamageOutFieldNumber = 9;
    private int heroDamageOut_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HeroDamageOut {
      get { return heroDamageOut_; }
      set {
        heroDamageOut_ = value;
      }
    }

    /// <summary>Field number for the "Skill_1_Dmg" field.</summary>
    public const int Skill1DmgFieldNumber = 10;
    private int skill1Dmg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Skill1Dmg {
      get { return skill1Dmg_; }
      set {
        skill1Dmg_ = value;
      }
    }

    /// <summary>Field number for the "Skill_1_Use" field.</summary>
    public const int Skill1UseFieldNumber = 11;
    private int skill1Use_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Skill1Use {
      get { return skill1Use_; }
      set {
        skill1Use_ = value;
      }
    }

    /// <summary>Field number for the "Skill_2_Dmg" field.</summary>
    public const int Skill2DmgFieldNumber = 12;
    private int skill2Dmg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Skill2Dmg {
      get { return skill2Dmg_; }
      set {
        skill2Dmg_ = value;
      }
    }

    /// <summary>Field number for the "Skill_2_Use" field.</summary>
    public const int Skill2UseFieldNumber = 13;
    private int skill2Use_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Skill2Use {
      get { return skill2Use_; }
      set {
        skill2Use_ = value;
      }
    }

    /// <summary>Field number for the "FuryUse" field.</summary>
    public const int FuryUseFieldNumber = 14;
    private int furyUse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FuryUse {
      get { return furyUse_; }
      set {
        furyUse_ = value;
      }
    }

    /// <summary>Field number for the "BattleResult" field.</summary>
    public const int BattleResultFieldNumber = 15;
    private int battleResult_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BattleResult {
      get { return battleResult_; }
      set {
        battleResult_ = value;
      }
    }

    /// <summary>Field number for the "Rank" field.</summary>
    public const int RankFieldNumber = 16;
    private int rank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "mVP" field.</summary>
    public const int MVPFieldNumber = 17;
    private bool mVP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MVP {
      get { return mVP_; }
      set {
        mVP_ = value;
      }
    }

    /// <summary>Field number for the "tripleKill" field.</summary>
    public const int TripleKillFieldNumber = 18;
    private bool tripleKill_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TripleKill {
      get { return tripleKill_; }
      set {
        tripleKill_ = value;
      }
    }

    /// <summary>Field number for the "megaKill" field.</summary>
    public const int MegaKillFieldNumber = 19;
    private bool megaKill_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MegaKill {
      get { return megaKill_; }
      set {
        megaKill_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerResultModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerResultModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if (HeroID != other.HeroID) return false;
      if (HeroTypeID != other.HeroTypeID) return false;
      if (Skill1 != other.Skill1) return false;
      if (Skill2 != other.Skill2) return false;
      if (Kill != other.Kill) return false;
      if (Death != other.Death) return false;
      if (HeroDamageIn != other.HeroDamageIn) return false;
      if (HeroDamageOut != other.HeroDamageOut) return false;
      if (Skill1Dmg != other.Skill1Dmg) return false;
      if (Skill1Use != other.Skill1Use) return false;
      if (Skill2Dmg != other.Skill2Dmg) return false;
      if (Skill2Use != other.Skill2Use) return false;
      if (FuryUse != other.FuryUse) return false;
      if (BattleResult != other.BattleResult) return false;
      if (Rank != other.Rank) return false;
      if (MVP != other.MVP) return false;
      if (TripleKill != other.TripleKill) return false;
      if (MegaKill != other.MegaKill) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID.Length != 0) hash ^= PlayerID.GetHashCode();
      if (HeroID.Length != 0) hash ^= HeroID.GetHashCode();
      if (HeroTypeID != 0) hash ^= HeroTypeID.GetHashCode();
      if (Skill1 != 0) hash ^= Skill1.GetHashCode();
      if (Skill2 != 0) hash ^= Skill2.GetHashCode();
      if (Kill != 0) hash ^= Kill.GetHashCode();
      if (Death != 0) hash ^= Death.GetHashCode();
      if (HeroDamageIn != 0) hash ^= HeroDamageIn.GetHashCode();
      if (HeroDamageOut != 0) hash ^= HeroDamageOut.GetHashCode();
      if (Skill1Dmg != 0) hash ^= Skill1Dmg.GetHashCode();
      if (Skill1Use != 0) hash ^= Skill1Use.GetHashCode();
      if (Skill2Dmg != 0) hash ^= Skill2Dmg.GetHashCode();
      if (Skill2Use != 0) hash ^= Skill2Use.GetHashCode();
      if (FuryUse != 0) hash ^= FuryUse.GetHashCode();
      if (BattleResult != 0) hash ^= BattleResult.GetHashCode();
      if (Rank != 0) hash ^= Rank.GetHashCode();
      if (MVP != false) hash ^= MVP.GetHashCode();
      if (TripleKill != false) hash ^= TripleKill.GetHashCode();
      if (MegaKill != false) hash ^= MegaKill.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PlayerID);
      }
      if (HeroID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(HeroID);
      }
      if (HeroTypeID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(HeroTypeID);
      }
      if (Skill1 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Skill1);
      }
      if (Skill2 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Skill2);
      }
      if (Kill != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Kill);
      }
      if (Death != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Death);
      }
      if (HeroDamageIn != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(HeroDamageIn);
      }
      if (HeroDamageOut != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(HeroDamageOut);
      }
      if (Skill1Dmg != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Skill1Dmg);
      }
      if (Skill1Use != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Skill1Use);
      }
      if (Skill2Dmg != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Skill2Dmg);
      }
      if (Skill2Use != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Skill2Use);
      }
      if (FuryUse != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(FuryUse);
      }
      if (BattleResult != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(BattleResult);
      }
      if (Rank != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Rank);
      }
      if (MVP != false) {
        output.WriteRawTag(136, 1);
        output.WriteBool(MVP);
      }
      if (TripleKill != false) {
        output.WriteRawTag(144, 1);
        output.WriteBool(TripleKill);
      }
      if (MegaKill != false) {
        output.WriteRawTag(152, 1);
        output.WriteBool(MegaKill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PlayerID);
      }
      if (HeroID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(HeroID);
      }
      if (HeroTypeID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(HeroTypeID);
      }
      if (Skill1 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Skill1);
      }
      if (Skill2 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Skill2);
      }
      if (Kill != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Kill);
      }
      if (Death != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Death);
      }
      if (HeroDamageIn != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(HeroDamageIn);
      }
      if (HeroDamageOut != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(HeroDamageOut);
      }
      if (Skill1Dmg != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Skill1Dmg);
      }
      if (Skill1Use != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Skill1Use);
      }
      if (Skill2Dmg != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Skill2Dmg);
      }
      if (Skill2Use != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Skill2Use);
      }
      if (FuryUse != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(FuryUse);
      }
      if (BattleResult != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(BattleResult);
      }
      if (Rank != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Rank);
      }
      if (MVP != false) {
        output.WriteRawTag(136, 1);
        output.WriteBool(MVP);
      }
      if (TripleKill != false) {
        output.WriteRawTag(144, 1);
        output.WriteBool(TripleKill);
      }
      if (MegaKill != false) {
        output.WriteRawTag(152, 1);
        output.WriteBool(MegaKill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerID);
      }
      if (HeroID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HeroID);
      }
      if (HeroTypeID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HeroTypeID);
      }
      if (Skill1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skill1);
      }
      if (Skill2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skill2);
      }
      if (Kill != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Kill);
      }
      if (Death != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Death);
      }
      if (HeroDamageIn != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HeroDamageIn);
      }
      if (HeroDamageOut != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HeroDamageOut);
      }
      if (Skill1Dmg != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skill1Dmg);
      }
      if (Skill1Use != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skill1Use);
      }
      if (Skill2Dmg != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skill2Dmg);
      }
      if (Skill2Use != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skill2Use);
      }
      if (FuryUse != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FuryUse);
      }
      if (BattleResult != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BattleResult);
      }
      if (Rank != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Rank);
      }
      if (MVP != false) {
        size += 2 + 1;
      }
      if (TripleKill != false) {
        size += 2 + 1;
      }
      if (MegaKill != false) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerResultModel other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID.Length != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.HeroID.Length != 0) {
        HeroID = other.HeroID;
      }
      if (other.HeroTypeID != 0) {
        HeroTypeID = other.HeroTypeID;
      }
      if (other.Skill1 != 0) {
        Skill1 = other.Skill1;
      }
      if (other.Skill2 != 0) {
        Skill2 = other.Skill2;
      }
      if (other.Kill != 0) {
        Kill = other.Kill;
      }
      if (other.Death != 0) {
        Death = other.Death;
      }
      if (other.HeroDamageIn != 0) {
        HeroDamageIn = other.HeroDamageIn;
      }
      if (other.HeroDamageOut != 0) {
        HeroDamageOut = other.HeroDamageOut;
      }
      if (other.Skill1Dmg != 0) {
        Skill1Dmg = other.Skill1Dmg;
      }
      if (other.Skill1Use != 0) {
        Skill1Use = other.Skill1Use;
      }
      if (other.Skill2Dmg != 0) {
        Skill2Dmg = other.Skill2Dmg;
      }
      if (other.Skill2Use != 0) {
        Skill2Use = other.Skill2Use;
      }
      if (other.FuryUse != 0) {
        FuryUse = other.FuryUse;
      }
      if (other.BattleResult != 0) {
        BattleResult = other.BattleResult;
      }
      if (other.Rank != 0) {
        Rank = other.Rank;
      }
      if (other.MVP != false) {
        MVP = other.MVP;
      }
      if (other.TripleKill != false) {
        TripleKill = other.TripleKill;
      }
      if (other.MegaKill != false) {
        MegaKill = other.MegaKill;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PlayerID = input.ReadString();
            break;
          }
          case 18: {
            HeroID = input.ReadString();
            break;
          }
          case 24: {
            HeroTypeID = input.ReadInt32();
            break;
          }
          case 32: {
            Skill1 = input.ReadInt32();
            break;
          }
          case 40: {
            Skill2 = input.ReadInt32();
            break;
          }
          case 48: {
            Kill = input.ReadInt32();
            break;
          }
          case 56: {
            Death = input.ReadInt32();
            break;
          }
          case 64: {
            HeroDamageIn = input.ReadInt32();
            break;
          }
          case 72: {
            HeroDamageOut = input.ReadInt32();
            break;
          }
          case 80: {
            Skill1Dmg = input.ReadInt32();
            break;
          }
          case 88: {
            Skill1Use = input.ReadInt32();
            break;
          }
          case 96: {
            Skill2Dmg = input.ReadInt32();
            break;
          }
          case 104: {
            Skill2Use = input.ReadInt32();
            break;
          }
          case 112: {
            FuryUse = input.ReadInt32();
            break;
          }
          case 120: {
            BattleResult = input.ReadInt32();
            break;
          }
          case 128: {
            Rank = input.ReadInt32();
            break;
          }
          case 136: {
            MVP = input.ReadBool();
            break;
          }
          case 144: {
            TripleKill = input.ReadBool();
            break;
          }
          case 152: {
            MegaKill = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PlayerID = input.ReadString();
            break;
          }
          case 18: {
            HeroID = input.ReadString();
            break;
          }
          case 24: {
            HeroTypeID = input.ReadInt32();
            break;
          }
          case 32: {
            Skill1 = input.ReadInt32();
            break;
          }
          case 40: {
            Skill2 = input.ReadInt32();
            break;
          }
          case 48: {
            Kill = input.ReadInt32();
            break;
          }
          case 56: {
            Death = input.ReadInt32();
            break;
          }
          case 64: {
            HeroDamageIn = input.ReadInt32();
            break;
          }
          case 72: {
            HeroDamageOut = input.ReadInt32();
            break;
          }
          case 80: {
            Skill1Dmg = input.ReadInt32();
            break;
          }
          case 88: {
            Skill1Use = input.ReadInt32();
            break;
          }
          case 96: {
            Skill2Dmg = input.ReadInt32();
            break;
          }
          case 104: {
            Skill2Use = input.ReadInt32();
            break;
          }
          case 112: {
            FuryUse = input.ReadInt32();
            break;
          }
          case 120: {
            BattleResult = input.ReadInt32();
            break;
          }
          case 128: {
            Rank = input.ReadInt32();
            break;
          }
          case 136: {
            MVP = input.ReadBool();
            break;
          }
          case 144: {
            TripleKill = input.ReadBool();
            break;
          }
          case 152: {
            MegaKill = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MatchResultReply : pb::IMessage<MatchResultReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MatchResultReply> _parser = new pb::MessageParser<MatchResultReply>(() => new MatchResultReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MatchResultReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Thetan.Shared.V1.MatchResultReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchResultReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchResultReply(MatchResultReply other) : this() {
      matchID_ = other.matchID_;
      playerResult_ = other.playerResult_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchResultReply Clone() {
      return new MatchResultReply(this);
    }

    /// <summary>Field number for the "matchID" field.</summary>
    public const int MatchIDFieldNumber = 1;
    private string matchID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MatchID {
      get { return matchID_; }
      set {
        matchID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playerResult" field.</summary>
    public const int PlayerResultFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Thetan.Shared.V1.PlayerResultModel> _repeated_playerResult_codec
        = pb::FieldCodec.ForMessage(18, global::Thetan.Shared.V1.PlayerResultModel.Parser);
    private readonly pbc::RepeatedField<global::Thetan.Shared.V1.PlayerResultModel> playerResult_ = new pbc::RepeatedField<global::Thetan.Shared.V1.PlayerResultModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Thetan.Shared.V1.PlayerResultModel> PlayerResult {
      get { return playerResult_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MatchResultReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MatchResultReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MatchID != other.MatchID) return false;
      if(!playerResult_.Equals(other.playerResult_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MatchID.Length != 0) hash ^= MatchID.GetHashCode();
      hash ^= playerResult_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MatchID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MatchID);
      }
      playerResult_.WriteTo(output, _repeated_playerResult_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MatchID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MatchID);
      }
      playerResult_.WriteTo(ref output, _repeated_playerResult_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MatchID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MatchID);
      }
      size += playerResult_.CalculateSize(_repeated_playerResult_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MatchResultReply other) {
      if (other == null) {
        return;
      }
      if (other.MatchID.Length != 0) {
        MatchID = other.MatchID;
      }
      playerResult_.Add(other.playerResult_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MatchID = input.ReadString();
            break;
          }
          case 18: {
            playerResult_.AddEntriesFrom(input, _repeated_playerResult_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MatchID = input.ReadString();
            break;
          }
          case 18: {
            playerResult_.AddEntriesFrom(ref input, _repeated_playerResult_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
