name: Release Unity

on:
  workflow_dispatch:

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build script
        run: | 
          ./unity/increment_version.sh
          
          go install github.com/sorcererxw/protoc-gen-go-grpc-mock@latest
          go install github.com/srikrsna/protoc-gen-gotag@latest

          export PATH=${PATH}:`go env GOPATH`/bin

          buf generate proto
          buf generate --template buf.gen.tag.yaml proto
          
          cp ./unity/package.json ./gen/csharp/package.json
          cp ./unity/Wolffun.Protobuf.asmdef ./gen/csharp/Wolffun.Protobuf.asmdef
        shell: bash

      - uses: EndBug/add-and-commit@v9

      - name: Run build script
        run: |
          ./unity/fix_meta.sh
        shell: bash
      - uses: EndBug/add-and-commit@v9
        with:
          tag: $VERSION
