name: Release Unity

on:
  workflow_dispatch:

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1

      - name: Run build script
        run: | 
          ./unity/increment_version.sh
          
          buf generate proto
          
          cp ./unity/package.json ./gen/csharp/package.json
          cp ./unity/Wolffun.Protobuf.asmdef ./gen/csharp/Wolffun.Protobuf.asmdef
          
          ./tools/unity-meta-check ./gen/csharp
          ./tools/unity-meta-autofix -root-dir ./gen/csharp .
          
          git status
          git add gen/*
          git commit -m "bot: generated code"
          
          git status
          git log
        shell: bash
