name: Release Unity

on:
  workflow_dispatch:

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build script
        run: | 
          ./unity/increment_version.sh
          cat ./unity/package.json
        shell: bash
