name: Release Unity

on:
  workflow_dispatch:

permissions:
  pull-requests: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: DeNA/unity-meta-check@v3
        with:
          enable_autofix: true
          enable_pr_comment: true
          pr_comment_pull_number: 2
          target_path: ./gen/csharp
          autofix_globs: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: See how autofix did
        run: git status
        if: always()
